apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-deployment
  labels:
    app: zhiyuan-playlist-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhiyuan-playlist-recommender
  template:
    metadata:
      labels:
        app: zhiyuan-playlist-recommender
    spec:
      containers:
        - name: recommend
          image: lolikon/playlist-recommender-system:0.16
          ports:
            - containerPort: 52004
          volumeMounts:
            - name: models-volume
              mountPath: /app/Models
            - name: dataset-volume
              mountPath: /app/Dataset
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: project2-pvc-zhiyuan
          # hostPath:
          #   path: /home/zhiyuan/project2-pv2/Models
          #   type: Directory
        - name: dataset-volume
          # persistentVolumeClaim:
          #   claimName: project2-pv2-zhiyuan
          hostPath:
            path: /home/zhiyuan/project2-pv2/Dataset
            type: Directory

# docker run -p 52004:52004 -v /home/zhiyuan/project2-pv2/Models:/app/models -v /home/zhiyuan/project2-pv2/Dataset:/app/dataset lolikon/playlist-recommender-system:0.12
