apiVersion: batch/v1
kind: Job
metadata:
  name: frequentitemsetmining-job
spec:
  template:
    metadata:
      labels:
        app: frequentitemsetmining
    spec:
      containers:
        - name: frequentitemsetmining
          image: lolikon/recommender-update-system:0.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: dataset-volume
              mountPath: /app/dataset
      restartPolicy: Never
      volumes:
        - name: models-volume
          hostPath:
            path: /home/zhiyuan/project2-pv2/Models
            type: Directory
        - name: dataset-volume
          hostPath:
            path: /home/zhiyuan/project2-pv2/Dataset
            type: Directory
  backoffLimit: 2
