apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-zhiyuan
  namespace: zhiyuan
spec:
  selector:
    matchLabels:
      namespace: zhiyuan
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
